POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0ODE4NzM1MiwidXNlcklkIjoyfQ.LMNE-fJ2OQend0tLQU7qof9NpPL4xXqcnv2DNPGSVJw

{
    "name": "Another Test Event",
    "description": "This is a test event",
    "location": "Manhattan",
    "datetime": "2025-05-25T19:01:43.6688243+05:30"
}