DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0ODE3NDMyMywidXNlcklkIjoxfQ.A7jGEECaXc0f_akxfS7yRR5uMeypXthe3g7_S8bya3s
