PUT http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0ODE4NzM1MiwidXNlcklkIjoyfQ.LMNE-fJ2OQend0tLQU7qof9NpPL4xXqcnv2DNPGSVJw

{
    "name": "Another Updated Test Event!!!",
    "description": "This is a test event(Updated!)",
    "location": "Manhattan (Updated!)"
}